### ISSUE TITLE
[Pedido de Adesão]

### ISSUE THREAD

**Issue by tnmendes** [swift-pt/swift-pt#2]
# 𝔊𝔲𝔦𝔩𝔡𝔞 𝔓𝔬𝔯𝔱𝔲𝔤𝔲𝔢𝔰𝔞 𝔡𝔢 𝔓𝔯𝔬𝔤𝔯𝔞𝔪𝔞𝔡𝔬𝔯𝔢𝔰 𝔢𝔪 𝔖𝔴𝔦𝔣𝔱
## Pedido de Adesão

Quero aderir à Guilda Portuguesa de Programadores em Swift.

Sou:
 * [x] Programador em Swift
 * [ ] Programador noutra(s) linguagem(ns) interessado em Swift
 * [ ] Não programador interessado em Swift
 * [ ] Amigo de programador(es) em Swift, interessado(s) em Swift ou não programador(es) interessado(s) em Swift
 * [ ] Todas as anteriores
 * [ ] Nenhuma das anteriores

e quero aderir a este Guilda porque tenho um fervoroso desejo de participar na partilha de informação e conhecimento sobre Swift, assim como outros temas vagamente relacionados, com outros portugueses, lusófonos ou pessoas remotamente associadas a Portugal.

**Comment by mmar** [comment]
Convite enviado.
